### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by azazellochg** [azazellochg/perfectem#1]
- [x] implement ACF check
- [ ] implement afis specs check
- [x] add a test for reloading cartridges and measure atlas realignment
- [x] add serialem python module to distribution so that it can be used remotely
